language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=2.0

install:
  - pip install django==$DJANGO
  - python setup.py install

script: python run_tests.py
