# Generated by Django 2.0.2 on 2018-03-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='время')),
                ('transaction_id', models.CharField(db_index=True, max_length=150, verbose_name='ID транзакции в платежном шлюзе')),
                ('testing', models.BooleanField(default=True, verbose_name='тестовая транзакция')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='сумма операции')),
                ('currency', models.CharField(max_length=3, verbose_name='валюта')),
                ('order_id', models.CharField(max_length=128, verbose_name='ID операции в магазине')),
                ('state', models.CharField(choices=[('COMPLETE', 'успешно'), ('FAILED', 'ошибка')], max_length=10, verbose_name='состояние')),
                ('message', models.TextField(blank=True, verbose_name='текст ошибки или сообщение об успешном совершении операции')),
                ('meta', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'платёж через Futubank',
                'verbose_name_plural': 'платежи через Futubank',
                'ordering': ('-creation_datetime',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('state', 'transaction_id')},
        ),
    ]
